<?php

/**
 * @file
 * Provide Views Style plugin for jScrollable.
 */

/**
 * Implementation of hook_views_api().
 */
function scrollable_views_api() {
  return array('api' => 2);
}

/**
 * Implementation of hook_theme().
 */
function scrollable_theme() {
  $path = drupal_get_path('module', 'scrollable') .'/theme';

  return array(
    'scrollable' => array(
      'template' => 'scrollable',
      'path' => $path,
      'arguments' => array('rows' => array(), 'options' => array()),
    ),
  );
}  

/**
 * Themes the Scrollable View.
 */
function theme_scrollable_view($view, $options = array(), $rows = array()) {
  //print_r($view);
  //print_r($options);
  //print_r($rows);
  
  $path = drupal_get_path('module', 'scrollable');
  drupal_add_js($path .'/js/jquery.scrollable.min.js');
  
  drupal_add_css($path .'/css/scrollable_'. (($options['vertical']) ? 'vertical' : 'horizontal') .'.css');
  
  if ( $options['mousewheel'] ) {
    drupal_add_js($path .'/js/jquery.mousewheel.min.js');
  }
  
  $js = '$(document).ready(function() {         
           // initialize scrollable  
           $("div.scrollable").scrollable({
             size: '. $options['size'] .',
             vertical: '. $options['vertical'] .',
             clickable: '. $options['clickable'] .',
             loop: '. $options['loop'] .',
             interval: '. $options['interval'] .',
             speed: '. $options['speed'] .',
             keyboard: '. $options['keyboard'] .',
             items: ".'. $options['items'] .'",
             prev: ".'. $options['prev'] .'",
             next: ".'. $options['next'] .'",
             prevPage: ".'. $options['prevPage'] .'",
             nextPage: ".'. $options['nextPage'] .'",
             navi: ".'. $options['navi'] .'",
             easing: "'. $options['easing'] .'",
           });     
         });';
  
  drupal_add_js($js, 'inline');
  
  return theme('scrollable', $rows, $options);
}