<?php
// $Id: alterprofilepage.module,v 1.3.2.3 2010/04/04 08:43:54 jerdiggity Exp $

/**
 * @file
 * Customizes the user profile page for a more "social-networking" look.
 */

/**
 * Implementation of hook_profile_alter().
 */
function alterprofilepage_profile_alter(&$account) {
  $account->content['user_picture']['#weight'] = -21;	// Keep the picture at the top like normal
  $account->content['summary']['#weight'] = -20;		// Keep the summary next to the picture
  $account->content['summary']['#title'] = NULL;		// If not NULL, two titles would show up (see line 46 below)
  $account->content['summary']['member_for']['#title'] = t('Member since');
  $account->content['summary']['member_for']['#weight'] = -19;
  $account->content['summary']['member_for']['#value'] = check_plain(strftime('%B %Y', $account->created));
  $hrsnow = time();
  $hrsago = $hrsnow - 300;
  $hrsago1 = $hrsnow - 1500;
  $hrsago2 = $hrsago1 - 3600;
  $hrsago3 = $hrsago2 - 7200;
  $hrsago4 = $hrsago3 - 10800;
  if ($hrsago <= $account->access) {
    $altppimgdir = base_path();
    $altppimgdir .= drupal_get_path('module', 'alterprofilepage');
    $altppimgdir .= '/online.gif';
	$altppurltxt = t('@name is online!', array('@name' => $account->name));
	$altppalttxt = t('Online');
    $lastlogintime = '<img src="'. $altppimgdir .'" title="'. $altppurltxt .'" alt="'. $altppalttxt .'" />';
  }
  elseif ($hrsago1 <= $account->access) {
    $lastlogintime = t('Within the past half hour');
  }
  elseif ($hrsago2 <= $account->access) {
    $lastlogintime = t('About an hour ago');
  }
  elseif ($hrsago3 <= $account->access) {
    $lastlogintime = t('A few hours ago');
  }
  elseif ($hrsago4 <= $account->access) {
    $lastlogintime = t('Several hours ago');
  }
  else {
    $lastlogintime = strftime('%x', $account->access);
  }
  $account->content['summary']['last_access'] = array(
  '#type' => 'user_profile_item',
  '#title' => t('Last login'),
  '#value' => $lastlogintime,
  '#weight' => -18,
  );
  drupal_set_title(t('@user\'s profile', array('@user' => $account->name)));
}
