<?php
// $Id: modalframe_path.module,v 1.1.2.2 2010/01/02 05:57:49 markuspetrux Exp $

/**
 * @file
 * Opens path administration forms in modal frames.
 */

/**
 * Implementation of hook_init().
 */
function modalframe_path_init() {
  if (!empty($_COOKIE['has_js']) && preg_match('`^admin/build/path(?:/list(?:/.*))?$`', $_GET['q'])) {
    modalframe_parent_js();
    drupal_add_js(drupal_get_path('module', 'modalframe_path') .'/modalframe_path.js');
  }
}

/**
 * Implementation of hook_form_alter().
 */
function modalframe_path_form_alter(&$form, $form_state, $form_id) {
  if (!empty($_COOKIE['has_js']) && !empty($_GET['modalframe']) && in_array($form_id, array('path_admin_form', 'path_admin_delete_confirm'))) {
    modalframe_child_js();
    $form['#submit'][] = 'modalframe_path_form_submit';
  }
}

/**
 * Process the path administration forms.
 */
function modalframe_path_form_submit($form, &$form_state) {
  modalframe_close_dialog(array('url' => url('admin/build/path', array('absolute' => TRUE))));
}
