<?php

/**
 * @file
 * Ogone payment module for Ubercart. No extra gateway needed.
 * For Ogone PSP
 * Please read de "readme.txt'!
 *
 * Development by Qrios | http://www.qrios.nl | c.kodde {at} qrios {dot} nl
 *
 *
 */



/**
 * Implementation of hook_payment_method().
 */
function uc_ogone_payment_payment_method() {
  $methods[] = array(
    'id' => 'ogone_payment',
    'name' => t('Ogone Payment'),
    'title' => t('Ogone Payment'),
    'desc' => t('Ogone payment method type.'),
    'callback' => 'uc_payment_method_ogone',
    'weight' => 2,
    'checkout' => TRUE,
    'backend' => TRUE,
  );

  return $methods;
}

/**
 * Implementation of hook_menu().
 */
function uc_ogone_payment_menu() {
  $items = array();

    $items['cart/checkout/ogone_redirect'] = array(
      'title' => 'Secure Payment Page',
      'page callback' => 'uc_ogone_redirect_form',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
    );

    $items['cart/ogone_return_ok'] = array(
      'title' => 'Ogone Payment return status',
      'page callback' => 'uc_ogone_return_ok',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
    );

    $items['cart/ogone_ok'] = array(
      'title' => 'Ogone Payment OK',
      'page callback' => 'uc_ogone_ok',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
    );

    $items['cart/ogone_false'] = array(
      'title' => 'Ogone Payment Error',
      'page callback' => 'uc_ogone_false',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
    );

    $items['cart/checkout/ogone_cancel'] = array(
      'title' => 'Ogone Payment cancel',
      'page callback' => 'uc_ogone_return_cancel',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
    );

    $items['ogone_template_call'] = array(
      'title' => 'Ogone Secure Payment',
      'page callback' => 'uc_ogone_template',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
    );

    $items['cart/ogone_return_ok_callback'] = array(
      'title' => 'Ogone Payment return status',
      'callback' => 'uc_ogone_return_ok_callback',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
    );

  return $items;
}


/**
 * Implementation of hook_order().
 */
function uc_ogone_payment_order($op, &$arg1, $arg2) {
  switch ($op) {
    case 'submit': //This is the place!
        //Called at submit [Submit order]
        if ($arg1->payment_method == 'ogone_payment') {
          uc_ogone_call($arg1, $arg2);
          exit;
        }
      break;

      case 'load':
        //echo 'load';
        //Called at "Review order" after  submit 'review order'
      break;

    case 'save':
        //echo 'save';
        //Called at submit [review order]
      if ($arg1->payment_method == 'ogone_payment') {
        //todo??
      }
      break;

    case 'delete':
      //db_query("DELETE FROM {uc_payment_credit} WHERE order_id = %d", $arg1);
      break;
  }
}

/*******************************************************************************
 * Callback Functions
 ******************************************************************************/

/**
 * Callback from hook payment_method
 */
function uc_payment_method_ogone($op, $arg1) {
  switch($op) {
    case 'order-view':
    case 'customer-view':
      $result = db_query("SELECT description FROM {uc_payment_ogone} WHERE "
                        ."order_id = %d", $arg1->order_id);
      if ($row = db_fetch_object($result)) {
        $output = t('Type:') .' '. $row->description;
      }
      else {
        $output = t('Type:') .' '. t('Unknown');
      }
      return $output;

    case 'order-details':
      $details = drupal_get_form('uc_ogone_payment_method_form', $arg1);
      return uc_strip_form($details);

    case 'edit-process':
      $changes['payment_details']['pm_ogone_description'] = check_plain($_POST['pm_ogone_description']);
      return $changes;

    case 'settings':
        return(uc_ogone_payment_settings_form());
        break;
    case 'order-load':
      $result = db_query("SELECT description FROM {uc_payment_ogone} WHERE "
                        ."order_id = %d", $arg1->order_id);
      if ($row = db_fetch_object($result)) {
        $arg1->payment_details['description'] = $row->description;
      }
      break;

    case 'order-save':
      db_query("DELETE FROM {uc_payment_ogone} WHERE order_id = %d", $arg1->order_id);
      if (strlen($arg1->payment_details['pm_ogone_description']) > 0) {
        db_query("INSERT INTO {uc_payment_ogone} (order_id, description) VALUES (%d, '%s')", $arg1->order_id, $arg1->payment_details['pm_ogone_description']);
      }
      break;
  }
}

function uc_ogone_payment_method_form($order) {
  $form['pm_ogone_description'] = array(
    '#type' => 'textfield',
    '#size' => 32,
    '#maxlength' => 64,
    '#default_value' => $order->payment_details['description'],
  );

  return $form;
}


function theme_uc_ogone_payment_method_form($form) {
  $output = '<table class="order-edit-table"><tr><td class="oet-label">jdkl'
          . t('Description:') .'</td><td>'
          . drupal_render($form['pm_ogone_description'])
          .'</td></tr></table>';
  return $output;
}


/**
 * Callback for payment gateway settings.
 */
function uc_ogone_payment_settings_form() {
  $form['ogone_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Ogone URL'),
    '#default_value' => variable_get('ogone_url', 'https://secure.ogone.com/ncol/test/orderstandard.asp'),
    '#description' => t('The URL for the Ogone PSP service. Use https://secure.ogone.com/ncol/test/orderstandard.asp for testpurposes, https://secure.ogone.com/ncol/prod/orderstandard.asp for production use.'),
  );
  $form['ogone_catalog_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Merchant catalog URL'),
    '#default_value' => variable_get('ogone_catalog_url', 'catalog'),
    '#description' => t('The relative path to your catalog page. For instance if your catalog page is www.yourdomain.com/catalog enter catalog'),
  );
  $form['ogone_pspid_id'] = array(
    '#type' => 'textfield',
    '#title' => t('pspid'),
    '#default_value' => variable_get('ogone_pspid_id', ''),
    '#description' => t('The login username for the Ogone PSP service.'),
  );
  $form['ogone_currency'] = array(
    '#type' => 'textfield',
    '#title' => t('Currency'),
    '#default_value' => variable_get('ogone_currency', 'EUR'),
    '#description' => t('Use "EUR", "USD" or "GBP" for currency. See Ogone documentation for details.'),
  );
  $form['ogone_language'] = array(
    '#type' => 'textfield',
    '#title' => t('Language'),
    '#default_value' => variable_get('ogone_language', 'en_US'),
    '#description' => t('Use "en_US" notation for language. See Ogone documentation for details.'),
  );
  //Layout
  $form['ogone_layout_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#default_value' => variable_get('ogone_layout_title', 'Secure Checkout'),
    '#description' => t('Shown in payment page.'),
  );
  $form['ogone_layout_bgcolor'] = array(
    '#type' => 'textfield',
    '#title' => t('BG Color'),
    '#default_value' => variable_get('ogone_layout_bgcolor', ''),
    '#description' => t('Background color payment page.(empty for default)'),
  );
  $form['ogone_layout_txtcolor'] = array(
    '#type' => 'textfield',
    '#title' => t('text Color'),
    '#default_value' => variable_get('ogone_layout_txtcolor', ''),
    '#description' => t('Text color payment page.(empty for default)'),
  );
  $form['ogone_layout_tblbgcolor'] = array(
    '#type' => 'textfield',
    '#title' => t('Table BG Color'),
    '#default_value' => variable_get('ogone_layout_tblbgcolor', ''),
    '#description' => t('Background color tables in payment page.(empty for default)'),
  );
  $form['ogone_layout_tbltxtcolor'] = array(
    '#type' => 'textfield',
    '#title' => t('Table Text Color'),
    '#default_value' => variable_get('ogone_layout_tbltxtcolor', ''),
    '#description' => t('Text color tables in payment page.(empty for default)'),
  );
  $form['ogone_layout_buttonbgcolor'] = array(
    '#type' => 'textfield',
    '#title' => t('Button Color'),
    '#default_value' => variable_get('ogone_layout_buttonbgcolor', ''),
    '#description' => t('Button color in payment page.(empty for default)'),
  );
  $form['ogone_layout_buttontxtcolor'] = array(
    '#type' => 'textfield',
    '#title' => t('Button Text Color'),
    '#default_value' => variable_get('ogone_layout_buttontxtcolor', ''),
    '#description' => t('Button text color in payment page.(empty for default)'),
  );
  $form['ogone_layout_logo'] = array(
    '#type' => 'textfield',
    '#title' => t('Logo Path'),
    '#default_value' => variable_get('ogone_layout_logo', ''),
    '#description' => t('Logo to use on payment page.(empty for none)'),
  );
  $form['ogone_layout_fonttype'] = array(
    '#type' => 'textfield',
    '#title' => t('Fonttype'),
    '#default_value' => variable_get('ogone_layout_fonttype', ''),
  );
  $form['ogone_sha1_signature_pre'] = array(
    '#type' => 'textfield',
    '#title' => t('SHA-1 Signature pre'),
    '#default_value' => variable_get('ogone_sha1_signature_pre', ''),
    '#description' => t('SHA-1 signature for pre payment verification.'),
  );
  $form['ogone_sha1_signature_post'] = array(
    '#type' => 'textfield',
    '#title' => t('SHA-1 Signature post'),
    '#default_value' => variable_get('ogone_sha1_signature_post', ''),
    '#description' => t('SHA-1 signature for post payment verification.'),
  );

  return $form;
}


function uc_ogone_call(&$arg1, $arg2) {

  /*global $user; //Todo: find a way to detect user language
  if (!($user->language)) {
    $language = 'en_US';
  }

  $currency_sign = substr(htmlspecialchars(uc_currency_format('0')),0,3);
  $currency_sign = htmlspecialchars($currency_sign);

  switch($currency_sign) { //This needs review! Doesn't work properly
    case '$':
      $currency = 'USD';
      break;

    case '£':
      $currency = 'GBP';
      break;

    //case "€":
    default:
      $currency = 'EUR';
      break;
  }*/ //Disabled KK 180608, autodetection needs work

  //$ogone_url = 'https://secure.ogone.com/ncol/prod/orderstandard.asp';
  $ogone_url = filter_xss(variable_get('ogone_url', TRUE));

  //Set base url
  $url_base = current(parse_url($_SERVER['HTTP_REFERER'])).'://'.$_SERVER['HTTP_HOST'].url();

  $pspid = filter_xss(variable_get('ogone_pspid_id', TRUE));
  $orderid = $arg1->order_id;
  $amount = round($arg1->order_total * 100);   //amount *100

  $currency = filter_xss(variable_get('ogone_currency', TRUE));
  $language = filter_xss(variable_get('ogone_language', 'en_US'));

  $layout_title = filter_xss(variable_get('ogone_layout_title', TRUE));
  $layout_bgcolor = filter_xss(variable_get('ogone_layout_bgcolor', TRUE));
  $layout_txtcolor = filter_xss(variable_get('ogone_layout_txtcolor', TRUE));
  $layout_tblbgcolor = filter_xss(variable_get('ogone_layout_tblbgcolor', TRUE));
  $layout_tbltxtcolor = filter_xss(variable_get('ogone_layout_tbltxtcolor', TRUE));
  $layout_buttonbgcolor = filter_xss(variable_get('ogone_layout_buttonbgcolor', TRUE));
  $layout_buttontxtcolor = filter_xss(variable_get('ogone_layout_buttontxtcolor', TRUE));
  $layout_logo = filter_xss(variable_get('ogone_layout_logo', TRUE));
  $layout_fonttype = filter_xss(variable_get('ogone_layout_fonttype', TRUE));
  $layout_template = $url_base.'/ogone_template_call';

  $redirect_accepturl = $url_base.'/cart/ogone_return_ok';
  $redirect_declineurl = $url_base.'/cart/checkout';
  $redirect_exceptionurl = $url_base.'/cart/checkout';
  $redirect_cancelurl = $url_base.'/cart/checkout/ogone_cancel';

  $order_description = variable_get('uc_store_name', 'Webshop').' order: '.$arg1->order_id;
  $customer_name = $arg1->delivery_first_name.' '.$arg1->delivery_last_name;
  $customer_name = substr($customer_name, 0, 35); //Make sure this is < 35 char, else Ogone freaks out
  $customer_email = $arg1->primary_email;
  $brand = '';
  $pm = '';
  $customer_zip = $arg1->delivery_postal_code;
  $customer_address = $arg1->delivery_street1.' '.$arg1->delivery_street2.' '.$arg1->delivery_street2.' '.$arg1->delivery_city;

  $redirect_message1 = t('One moment please, you will automaticaly be redirected to the payment gateway...');
  $redirect_message2 = t('Popupblockers might stop the paymentpage from opening, please click the button to open the payment page if it does not open automaticaly.');
  $ogone_button_text = t('Click here to go to payment page manualy');

  // Disabled 060410 KK, duplicate?
  // $orderid = $arg1->order_id;
  // $amount = round($arg1->order_total * 100);   //amount *100

  $sha_suffix = variable_get('ogone_sha1_signature_pre', TRUE);

  //Make SHA1 string for pre payment verification
  $arguments = array(
    'ACCEPTURL' => $redirect_accepturl,
    'AMOUNT' => $amount,
    'BGCOLOR' => $layout_bgcolor,
    'BRAND' => '',
    'BUTTONBGCOLOR' => $layout_buttonbgcolor,
    'BUTTONTXTCOLOR' => $layout_buttontxtcolor,
    'CANCELURL' => $redirect_cancelurl,
    'CATALOGURL' => $url_base.'/'.$catalog_url,
    'CN' => $customer_name,
    'COM' => $order_description,
    'CURRENCY' => $currency,
    'DECLINEURL' => $redirect_declineurl,
    'EMAIL' => $customer_email,
    'EXCEPTIONURL' => $redirect_exceptionurl,
    'FONTTYPE' => $layout_fonttype,
    'HOMEURL' => $url_base,
    'LANGUAGE' => $language,
    'LOGO' => $layout_logo,
    'ORDERID' => $orderid,
    'OWNERADDRESS' => $customer_address,
    'OWNERZIP' => $customer_zip,
    'PM' => '',
    'PSPID' => $pspid,
    'TBLBGCOLOR' => $layout_tblbgcolor,
    'TBLTXTCOLOR' => $layout_tbltxtcolor,
    'TITLE' => $layout_title,
    'TP' => $layout_template,
    'TXTCOLOR' => $layout_tbltxtcolor
  );

  $sha1_signature = '';

  $_SESSION['ogone_order_id'] = $arg1->order_id;
  $_SESSION['ogone_form']='
  <div class="ogone_redirect_message_top">
  '.$redirect_message1.'
  </div>
  <div class="ogone_redirect_container">
  <div align="center" class="ogone_redirect_form">
  <FORM METHOD="post" ACTION="'.$ogone_url.'" id="ogone_form" name="ogone_form"  '. /*target="ogone_popup" */ 'onsubmit="">';

  foreach ($arguments as $param_name => $param_value) {
    $param_value = trim($param_value);
    $param_name = strtoupper($param_name);
    if (strlen($param_value) > 0) {
        $sha1_signature .= $param_name.'='.$param_value.$sha_suffix;
        $_SESSION['ogone_form'] .= '<INPUT type="hidden" NAME="'.$param_name.'" VALUE="'.$param_value.'" />';
    }
  }

  $_SESSION['ogone_form'] .= '
  <INPUT type="hidden" NAME="SHASign" value="'.sha1($sha1_signature).'">
  <input type="submit" value="'.$ogone_button_text.'" id="submit2" name="submit2" />
  </form>
  <script language="JavaScript">
  document.ogone_form.submit();
  </script>
  </div>
  <div class="ogone_redirect_message_bottom">
  '.$redirect_message2.'
  </div>
  </div>'
  ;
  drupal_goto('cart/checkout/ogone_redirect');
}


function uc_ogone_ok() {
  $result = db_query("SELECT sha1_test_succes, order_status FROM {uc_payment_ogone} WHERE order_id = %d", $_SESSION['ogone_order_id']);
  $ogone_order = db_fetch_object($result);
  //Debug
  //print_r($ogone_order);
  //exit;
  //Define valid statusses
  $valid_stat = array(5, 9);

  if ($ogone_order->sha1_test_succes == 'OK' && in_array($ogone_order->order_status, $valid_stat)){
    uc_order_update_status($_SESSION['ogone_order_id'], uc_order_state_default('payment_received'));

    //Debug
    //drupal_set_message('cartid:'.uc_cart_get_id().' ogone order id:'.$_SESSION['ogone_order_id']);

    // Ensure the cart we're looking at is the one that payment was attempted for.
    $_SESSION['cart_order'] = $_SESSION['ogone_order_id'];
    unset($_SESSION['ogone_order_id']);

    // This lets us know it's a legitimate access of the complete page.
    $_SESSION['do_complete'] = TRUE;

    drupal_goto('cart/checkout/complete');
  }else{
    drupal_goto('cart/ogone_false');
  }
}

function uc_ogone_false() {
  drupal_set_message(t('Ogone returned an error for your payment. Your order is not completed. Please try again or contact us.'), 'ERROR');
  watchdog('uc_ogone_payment', 'Ogone returned an error for this payment.', NULL, WATCHDOG_ERROR);
  drupal_goto('cart/checkout');
}

function uc_ogone_template() {
  $template = '<html><head><title>'.filter_xss(variable_get('ogone_layout_title', TRUE)).'</title></head><body style="background-color: #dfdfdf;">';
  $template .= '<div align="center"><div align="left" style="width: 550px; padding: 10px; border:2px solid #666; background-color: #fff;">';
  $template .= '<h1>'.filter_xss(variable_get('ogone_layout_title', TRUE)).'</h1>';
  $template .= '$$$PAYMENT ZONE$$$';
  $template .= '</div></div></body></html>';
  print $template;
  exit;
}

function uc_ogone_return_cancel() {
  drupal_set_message(t('Ogone returned a cancel for your payment. Your order is not completed. Please try again or contact us.'), 'ERROR');
  drupal_goto('cart/checkout');
}

function uc_ogone_redirect_form() {
  if ($_SESSION['ogone_form'] !== FALSE) {
    drupal_add_css(drupal_get_path('module', 'uc_ogone_payment') .'/uc_ogone_payment_form.css');
    $ogone_form = $_SESSION['ogone_form'];
    $_SESSION['ogone_form'] = FALSE;
    return($ogone_form );
  }else{
    drupal_goto('cart/');
  }
}

//This is caled by Ogone itself NOT within the user session!
function uc_ogone_return_ok($auto = FALSE) {

  $valid_stat = array(5, 9);
  $sha_suffix = variable_get('ogone_sha1_signature_post', TRUE);

  $arguments = array(
    'AAVCHECK' => trim($_GET['AAVCheck']),
    'ACCEPTANCE' => trim($_GET['ACCEPTANCE']),
    'AMOUNT' => trim($_GET['amount']),
    'BRAND' => trim($_GET['BRAND']),
    'CARDNO' => trim($_GET['CARDNO']),
    'CCCTY'=> trim($_GET['CCCTY']),
    'CN' => trim($_GET['CN']),
    'CURRENCY' => trim($_GET['currency']),
    'CVCCHECK' => trim($_GET['CVCCheck']),
    'ECI' => trim($_GET['ECI']),
    'ED' => trim($_GET['ED']),
    'IP' => trim($_GET['IP']),
    'IPCTY' => trim($_GET['IPCTY']),
    'NCERROR' => trim($_GET['NCERROR']),
    'ORDERID' => trim($_GET['orderID']),
    'PAYID' => trim($_GET['PAYID']),
    'PM' => trim($_GET['PM']),
    'STATUS' => trim($_GET['STATUS']),
    'TRXDATE' => trim($_GET['TRXDATE']),
    'VC' => trim($_GET['VC'])
  );

  $sha1_return_key = strtoupper($_GET['SHASIGN']);

  $sha1_key='';

  foreach ($arguments as $param_name => $param_value) {
    $param_value = trim($param_value);
    $param_name = strtoupper($param_name);
    if (strlen($param_value) > 0) {
      $sha1_key .= $param_name.'='.$param_value.$sha_suffix;
    }
  }

  $sha1_key = strtoupper(sha1($sha1_key));

  //Uncomment for manual SHA comparison for debug purposes
  // echo $sha1_return_key.'<br>'.$sha1_key;
  // exit;

  if (($sha1_key == $sha1_return_key) && in_array($arguments['STATUS'], $valid_stat)) {
    db_query("INSERT INTO {uc_payment_ogone} (order_id, description, payment_method, order_status, sha1_test_succes) VALUES ('%d','%s','%s','%s','%s')", $arguments['ORDERID'], 'Back-office' ,$arguments['PM'], $arguments['STATUS'], 'OK');
    if (!$auto) {
      drupal_goto('cart/ogone_ok');
    }
  } else {
    if (!$auto) {
      drupal_goto('cart/ogone_false');
    }
  }
}

//Can be used optionally to let Ogone return the payment status automatically/unmanaged
function uc_ogone_return_ok_callback() {
  uc_ogone_return_ok(TRUE);
}

?>